apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-pass # Use Release.Name for unique naming
type: Opaque
data:
  # The password is taken from values.yaml and base64 encoded
  password: {{ .Values.mysql.rootPassword | b64enc }}