apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: shay1987/login:latest
          imagePullPolicy: Always # Ensure this is 'Always' as previously discussed
          ports:
            - containerPort: 5000
          env:
          - name: FLASK_APP
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: FLASK_APP
          - name: MYSQL_ROOT_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_USER
          # --- CRITICAL FIX HERE ---
          # Source MYSQL_ROOT_PASSWORD from the Secret 'mysql-pass'
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password # 'password' is the key within your mysql-pass Secret
          - name: MYSQL_ROOT_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_HOST
          - name: MYSQL_ROOT_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_PORT
          - name: MYSQL_ROOT_DB
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MYSQL_ROOT_DB

---

apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  type: ClusterIP # Changed from NodePort to ClusterIP, which is fine as Ingress handles external access
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000