replicaCount: 1

image:
  login:
    repository: shay1987/login
    tag: latest
    pullPolicy: IfNotPresent
  arcade:
    repository: shay1987/arcade
    tag: latest
    pullPolicy: IfNotPresent
  mysql:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

mysql:
  rootPassword: admin
  database: mydb
  user: root
  port: 3306
  pvc:
    size: 1Gi
  service:
    type: ClusterIP

loginApp:
  secretKey: "change-this-in-production"
  service:
    type: ClusterIP
    port: 5000

arcadeApp:
  service:
    type: ClusterIP
    port: 7681

ingress:
  enabled: true
  className: nginx

resources:
  login:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  arcade:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  mysql:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
