apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcade-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arcade
  template:
    metadata:
      labels:
        app: arcade
    spec:
      containers:
        - name: arcade
          image: shay1987/arcade:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: arcade-service
spec:
  selector:
    app: arcade
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
