apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcade-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcade
  template:
    metadata:
      labels:
        app: arcade
    spec:
      containers:
        - name: arcade
          image: shay1987/arcade:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7681 # Explicitly declare container port for clarity
---
apiVersion: v1
kind: Service
metadata:
  name: arcade-service # This is the service name referenced in login.py
spec:
  selector:
    app: arcade
  ports:
    - protocol: TCP
      port: 5000       # Service listens on 5000 (as login.py expects)
      targetPort: 7681 # <--- CORRECTED: Target the actual container port
  type: ClusterIP