apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcade-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcade
  template:
    metadata:
      labels:
        app: arcade
    spec:
      containers:
        - name: arcade
          image: shay1987/arcade:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7681
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /arcade/
              port: 7681
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /arcade/
              port: 7681
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: arcade-svc
spec:
  selector:
    app: arcade
  ports:
    - protocol: TCP
      port: 7681
      targetPort: 7681
  type: ClusterIP
